# https://knplabs.com/fr/blog/how-to-dockerise-a-symfony-4-project
# https://github.com/bourdeau/docker-symfony4

version:  '3.7'
services:
  # https://hub.docker.com/r/mdillon/postgis/
  postgis:
    image: mdillon/postgis
    restart: on-failure
    environment:
      POSTGRES_DB: toto
      POSTGRES_USER: toto
      POSTGRES_PASSWORD: toto
    ports:
      - '5432:5432'

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './app:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8080:80'
    depends_on:
      - php

  php:
#    image: php:7.2-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './app:/usr/src/app'
    env_file:
      - .env
#    # bash user id
#    user: 501:501
    depends_on:
      - postgis

